[package]
name = "alpha-tak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tak = {path = "../tak"}
tch = { git = "https://github.com/LaurentMazare/tch-rs", branch = "main" }
rand = "0.8"
lazy_static = "1.4"
arrayvec = "0.7"
rayon = "1.5"
